org: ciucol
app: prueba-mun
service: pruebamun

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  getUsers:
    handler: handlerUsers.getUsers
    events:
      - http:
          path: users
          method: get

  newUser:
    handler: handlerUsers.newUser
    events:
      - http:
          path: users
          method: post

  getOrderByUser:
    handler: handlerOrders.getOrderByUser
    events:
      - http:
          path: orders/{id}
          method: get
  
  newOrder:
    handler: handlerOrders.newOrder
    events:
      - http:
          path: orders
          method: post

  updateBalance:
    handler: handlerBalance.updateBalance
    events:
      - http:
          path: users/{id}/balance
          method: put
  
  transfer:
    handler: handlerBalance.transfer
    events:
      - http:
          path: transfers
          method: post
  
  
plugins:
  - serverless-offline
