service: pruebamun

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  newUser:
    handler: handlerUsers.newUser
    events:
      - http:
          path: users
          method: post

  newOrder:
    handler: handlerOrders.newOrder
    events:
      - http:
          path: orders
          method: post

  increaseBalance:
    handler: handlerBalance.increaseBalance
    events:
      - http:
          path: increase-balance
          method: post
  
  transfer:
    handler: handlerBalance.transfer
    events:
      - http:
          path: transfers
          method: post
  
  
plugins:
  - serverless-offline
